"""
pr_creator.py — Automatically opens a GitHub Pull Request from the AI_Fix branch.

Uses only stdlib urllib so no extra dependency is required.
The GITHUB_TOKEN from .env must have `repo` write scope.
"""
import os
import re
import json
import logging
import urllib.request
import urllib.error
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("pr_creator")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_API = "https://api.github.com"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _parse_owner_repo(repo_url: str) -> tuple[str, str]:
    """
    Extract (owner, repo) from a GitHub URL.
    Handles:
      https://github.com/owner/repo.git
      https://github.com/owner/repo
      git@github.com:owner/repo.git
    """
    repo_url = repo_url.strip().rstrip("/")
    # SSH style: git@github.com:owner/repo.git
    ssh_match = re.match(r"git@github\.com:([^/]+)/(.+?)(?:\.git)?$", repo_url)
    if ssh_match:
        return ssh_match.group(1), ssh_match.group(2)
    # HTTPS style
    https_match = re.match(r"https?://(?:[^@]+@)?github\.com/([^/]+)/(.+?)(?:\.git)?$", repo_url)
    if https_match:
        return https_match.group(1), https_match.group(2)
    raise ValueError(f"Cannot parse owner/repo from URL: {repo_url}")


def _gh_request(method: str, path: str, body: dict | None = None) -> dict:
    """Make an authenticated GitHub API request, return parsed JSON."""
    url = f"{GITHUB_API}{path}"
    data = json.dumps(body).encode() if body else None
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json",
        "User-Agent": "RIFT-DevOps-Agent/1.0",
    }
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode(errors="replace")
        raise RuntimeError(f"GitHub API {method} {path} → {e.code}: {body_text}") from e


def _get_default_branch(owner: str, repo: str) -> str:
    """Return the repo's default branch (usually 'main' or 'master')."""
    try:
        info = _gh_request("GET", f"/repos/{owner}/{repo}")
        return info.get("default_branch", "main")
    except Exception:
        return "main"


def _build_pr_body(
    fixes: list[dict],
    failures: list[dict],
    score: dict,
    run_id: str,
    total_time_seconds: int,
) -> str:
    """Build a rich markdown body for the Pull Request."""
    total_fixes = len([f for f in fixes if f.get("status") == "FIXED"])
    total_failures = len(failures) + len(fixes)

    # Score breakdown
    base = score.get("base_score", 100) if isinstance(score, dict) else 100
    bonus = score.get("speed_bonus", 0) if isinstance(score, dict) else 0
    penalty = score.get("efficiency_penalty", 0) if isinstance(score, dict) else 0
    total_score = score.get("total", base + bonus - penalty) if isinstance(score, dict) else score

    minutes = total_time_seconds // 60
    seconds = total_time_seconds % 60

    # Build fixes table
    if fixes:
        table_rows = "\n".join(
            f"| `{f['file']}` | `{f['bug_type']}` | L{f.get('line_number', '?')} | {f.get('status', '?')} |"
            for f in fixes
        )
        fixes_table = (
            "| File | Bug Type | Line | Status |\n"
            "|------|----------|------|--------|\n"
            + table_rows
        )
    else:
        fixes_table = "_No fixes recorded._"

    return f"""## 🤖 Autonomous DevOps Agent — AI Fix Report

> This PR was automatically created by the **RIFT AI Agent**.  
> All commits are prefixed with `[AI-AGENT]` and were made to this branch only — `main` was never touched.

---

### 📊 Run Summary

| Metric | Value |
|--------|-------|
| **Run ID** | `{run_id}` |
| **Failures Detected** | {total_failures} |
| **Fixes Applied** | {total_fixes} |
| **Time Taken** | {minutes}m {seconds}s |
| **Final Score** | {total_score} (base {base} + speed {bonus} - penalty {penalty}) |

---

### 🔧 Fixes Applied

{fixes_table}

---

### 🔍 Bug Types Fixed

{", ".join(sorted(set(f.get("bug_type", "?") for f in fixes))) or "_None_"}

---

*Generated by [RIFT Autonomous DevOps Agent](https://github.com/rift-agent) · Run `{run_id[:8]}`*
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def create_pr(
    repo_url: str,
    branch_name: str,
    fixes: list[dict],
    failures: list[dict],
    score,
    run_id: str,
    total_time_seconds: int = 0,
) -> str | None:
    """
    Open a Pull Request from `branch_name` → default branch on GitHub.

    Returns the PR HTML URL on success, or None if creation fails
    (e.g. no token, already exists, empty diff).
    """
    if not GITHUB_TOKEN:
        logger.warning("[pr_creator] GITHUB_TOKEN not set — skipping PR creation.")
        return None

    try:
        owner, repo = _parse_owner_repo(repo_url)
    except ValueError as e:
        logger.warning(f"[pr_creator] {e}")
        return None

    base_branch = _get_default_branch(owner, repo)

    title = f"[AI-AGENT] Automated fixes — {branch_name}"
    body = _build_pr_body(fixes, failures, score, run_id, total_time_seconds)

    try:
        pr = _gh_request(
            "POST",
            f"/repos/{owner}/{repo}/pulls",
            body={
                "title": title,
                "body": body,
                "head": branch_name,
                "base": base_branch,
                "draft": False,
            },
        )
        pr_url = pr.get("html_url", "")
        logger.info(f"[pr_creator] PR created: {pr_url}")
        return pr_url

    except RuntimeError as e:
        err = str(e)
        if "422" in err and "already exists" in err.lower():
            logger.info("[pr_creator] PR already exists for this branch — skipping.")
        elif "422" in err and "no commits" in err.lower():
            logger.info("[pr_creator] No new commits on branch vs base — skipping PR.")
        else:
            logger.warning(f"[pr_creator] Could not create PR: {e}")
        return None
